openapi: 3.1.0
paths:
  /:
    get:
      operationId: getHealthStatus
      parameters: []
      responses:
        '200':
          description: Health status
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: OK
        default:
          description: Default error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultErrorDTO'
      summary: Get the health status of the application
      tags:
        - health
      x-speakeasy-group: health
      x-speakeasy-name-override: get
  /v1/organizations/{organizationId}/workspaces:
    servers:
      - url: https://gateway.cribl.cloud
    post:
      description: Create a new Workspace in the specified Organization.
      operationId: v1.workspaces.createWorkspace
      x-speakeasy-entity-operation: Workspace#create
      parameters:
        - name: organizationId
          required: true
          in: path
          description: >-
            The <code>id</code> of the Organization where you want to create the
            Workspace.
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WorkspaceCreateRequestDTO'
      responses:
        '201':
          description: The Workspace has been successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkspaceSchema'
        default:
          description: Default error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultErrorDTO'
      summary: Create a Workspace in the specified Organization
      tags:
        - workspaces
    get:
      description: Get a list of all Workspaces for the specified Organization.
      operationId: v1.workspaces.listWorkspaces
      x-speakeasy-entity-operation: Workspaces#read
      parameters:
        - name: organizationId
          required: true
          in: path
          description: >-
            The <code>id</code> of the Organization that contains the
            Workspaces.
          schema:
            type: string
      responses:
        '200':
          description: List of Workspaces has been successfully retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkspacesListResponseDTO'
        default:
          description: Default error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultErrorDTO'
      summary: List all Workspaces for the specified Organization
      tags:
        - workspaces
  /v1/organizations/{organizationId}/workspaces/{workspaceId}:
    servers:
      - url: https://gateway.cribl.cloud
    patch:
      description: Update the specified Workspace.
      operationId: v1.workspaces.updateWorkspace
      x-speakeasy-entity-operation: Workspace#update
      parameters:
        - name: organizationId
          required: true
          in: path
          description: The <code>id</code> of the Organization that contains the Workspace.
          schema:
            type: string
        - name: workspaceId
          required: true
          in: path
          description: The <code>id</code> of the Workspace to update.
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WorkspacePatchRequestDTO'
      responses:
        '204':
          description: The Workspace has been successfully updated
        default:
          description: Default error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultErrorDTO'
      summary: Update a Workspace
      tags:
        - workspaces
    delete:
      description: Delete the specified Workspace in the specified Organization.
      operationId: v1.workspaces.deleteWorkspace
      x-speakeasy-entity-operation: Workspace#delete
      parameters:
        - name: organizationId
          required: true
          in: path
          description: The <code>id</code> of the Organization that contains the Workspace.
          schema:
            type: string
        - name: workspaceId
          required: true
          in: path
          description: The <code>id</code> of the Workspace to delete.
          schema:
            type: string
      responses:
        '202':
          description: The Workspace deletion has been accepted
        default:
          description: Default error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultErrorDTO'
      summary: Delete a Workspace
      tags:
        - workspaces
    get:
      description: Get the specified Workspace.
      operationId: v1.workspaces.getWorkspace
      x-speakeasy-entity-operation: Workspace#get
      parameters:
        - name: organizationId
          required: true
          in: path
          description: The <code>id</code> of the Organization that contains the Workspace.
          schema:
            type: string
        - name: workspaceId
          required: true
          in: path
          description: The <code>id</code> of the Workspace to get.
          schema:
            type: string
      responses:
        '200':
          description: The Workspace details have been retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkspaceSchema'
        default:
          description: Default error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultErrorDTO'
      summary: Get a Workspace
      tags:
        - workspaces
components:
  schemas:
    AWSRegions:
      type: string
      enum:
        - us-west-2
        - us-east-1
        - us-east-2
        - eu-central-1
        - eu-central-2
        - eu-west-2
        - ap-southeast-1
        - ap-southeast-2
        - ca-central-1
      description: AWS region where the workspace is deployed
      x-speakeasy-unknown-values: allow
    WorkspaceState:
      type: string
      enum:
        - Provisioning
        - Active
        - Inactive
        - Failed
        - Deprovisioning
      description: Current state of the workspace
      x-speakeasy-unknown-values: allow
    WorkspaceSchema:
      type: object
      properties:
        workspaceId:
          type: string
          description: Unique identifier for the workspace
          minLength: 4
          maxLength: 41
          pattern: ^[a-z0-9]*$
          example: main
        region:
          description: AWS region where the workspace is deployed
          example: us-west-2
          allOf:
            - $ref: '#/components/schemas/AWSRegions'
        leaderFQDN:
          type: string
          description: Fully Qualified Domain Name of the workspace leader
          example: workspace-leader.example.com
        state:
          description: Current state of the workspace
          example: Active
          allOf:
            - $ref: '#/components/schemas/WorkspaceState'
        alias:
          type: string
          description: User-friendly alias for the workspace
          example: Production Environment
        description:
          type: string
          description: Detailed description of the workspace
          example: Main production workspace for customer data processing
        tags:
          description: Tags associated with the workspace
          example:
            - production
            - customer-data
          type: array
          items:
            type: string
      required:
        - workspaceId
        - region
        - leaderFQDN
        - state
    WorkspaceCreateRequestDTO:
      type: object
      properties:
        workspaceId:
          type: string
          description: Unique identifier for the workspace
          minLength: 4
          maxLength: 41
          pattern: ^[a-z0-9]*$
          example: main
        alias:
          type: string
          description: User-friendly alias for the workspace
          example: Production Environment
        description:
          type: string
          description: Detailed description of the workspace
          example: Main production workspace for customer data processing
        tags:
          description: Tags associated with the workspace
          example:
            - production
            - customer-data
          type: array
          items:
            type: string
      required:
        - workspaceId
    WorkspacePatchRequestDTO:
      type: object
      properties:
        alias:
          type: string
          description: User-friendly alias for the workspace
          example: Production Environment
        description:
          type: string
          description: Detailed description of the workspace
          example: Main production workspace for customer data processing
        tags:
          description: Tags associated with the workspace
          example:
            - production
            - customer-data
          type: array
          items:
            type: string
    WorkspacesListResponseDTO:
      type: object
      properties:
        items:
          description: List of workspaces
          type: array
          items:
            $ref: '#/components/schemas/WorkspaceSchema'
        count:
          type: number
          description: Total number of workspaces
          example: 5
          x-speakeasy-ignore: true
      required:
        - items
        - count
    DefaultErrorDTO:
      type: object
      properties:
        statusCode:
          type: number
        message:
          type: string
      required:
        - statusCode
        - message
x-speakeasy-retries:
  strategy: backoff
  backoff:
    initialInterval: 500
    maxInterval: 60000
    maxElapsedTime: 3600000
    exponent: 1.5
  statusCodes:
    - '502'
    - '503'
    - '504'
  retryConnectionErrors: true